# Generated by Django 4.2.17 on 2025-01-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact2',
            new_name='Contact3',
        ),
    ]
