# Generated by Django 4.2.17 on 2025-01-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_contact2_contact3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100, null=True)),
                ('texts', models.EmailField(max_length=255, null=True)),
            ],
        ),
    ]
