# Generated by Django 4.2.17 on 2025-02-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='s_texts',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
